from pydantic import BaseModel, Field
from typing import Optional, List, Literal, Any

class Query(BaseModel):
    """
    Represents an incoming user query.
    """
    text: str = Field(..., description="The text of the user's query.")
    file_path: Optional[str] = Field(None, description="Path to an attached file, if any.")

class RouterDecision(BaseModel):
    """
    Represents the decision made by the router.
    """
    agent: Literal["web_search", "multimodal"] = Field(..., description="The agent selected to handle the query.")
    reasoning: str = Field(..., description="The reasoning behind the routing decision.")

class AgentResponse(BaseModel):
    """
    Represents the response from an agent.
    """
    content: str = Field(..., description="The textual answer or summary generated by the agent.")
    source: str = Field(..., description="The source of the information (e.g., 'Web Search', 'PDF Analysis').")
    metadata: Optional[dict[str, Any]] = Field(default_factory=dict, description="Additional metadata about the response.")
